### ISSUE TITLE
Application porting guide missing

### ISSUE THREAD

**Issue by marianeichholz** [rugui/rugui#32]
Programmers new to RuGUI fall into a "no way back" trap. Old guides, tutorials and example programs won't work, and an installation with old tools is ... not helping, either.

So I really see an advantage in recommendations for porting existing applications, like the hanoi-gui-program, the simple calculator and so on.

Some aspects, I could resolve right now.
- The resources now live in app/resources/xml/main_view.xml
- The resource file must be converted like so:
  `gtk-builder-convert app/resources/{glade/main_view.glade,xml/main_view.xml}`
- 'glade app/resources/xml/main_view.xml` will emit a warning about GTK2/GTK3 compatibility issues, that cease after the first save.
- The Rakefile must `require 'rdoc/task'` instead of `require 'rake/rdoctask'`

After these quick hacks, the **simple_calculator** would boot, but it crashes on the first button event.

Of course the crash stack dumps have to be explored, as well as the differences between old scaffolded code and new one...

Stay tuned - Marian

**Comment by marianeichholz** [comment]
Here is the crash report:

```
`home/marian/src/scratch/simple_calculator_port/app/controllers/main_controller.rb:28:in `block (2 levels) in <class:MainController>': undefined method `[]' for nil:NilClass
     from /home/marian/.rvm/gems/ruby-1.9.3-p392/gems/rugui-2.0.0.beta2/lib/rugui/framework_adapters/GTK.rb:142:in `instance_exec'
     from /home/marian/.rvm/gems/ruby-1.9.3-p392/gems/rugui-2.0.0.beta2/lib/rugui/framework_adapters/GTK.rb:142:in `block in connect_declared_signal_block'
     from /home/marian/.rvm/gems/ruby-1.9.3-p392/gems/rugui-2.0.0.beta2/lib/rugui/framework_adapters/GTK.rb:86:in `call'
     from /home/marian/.rvm/gems/ruby-1.9.3-p392/gems/rugui-2.0.0.beta2/lib/rugui/framework_adapters/GTK.rb:86:in `main'
     from /home/marian/.rvm/gems/ruby-1.9.3-p392/gems/rugui-2.0.0.beta2/lib/rugui/framework_adapters/GTK.rb:86:in `run'
     from /home/marian/.rvm/gems/ruby-1.9.3-p392/gems/rugui-2.0.0.beta2/lib/rugui/base_controller.rb:231:in `run'
```

(rest omitted)

The libraries and versions are like this:
- ruby 1.9.3p392
- activesupport (3.2.12, 3.2.11, 3.2.9, 3.2.8, 3.1.12)
- rubigen (1.5.8)
- rake (10.0.4, 10.0.3, 10.0.2, 0.9.2.2)
- rugui (2.0.0.beta2)
- rvm (1.11.3.6, 1.11.3.5)
- glib2 (2.0.0)
- gtk2 (2.0.0)

I really should tidy that up...
